# Generated by Django 4.2.27 on 2026-02-12 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0008_book_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('model_name', models.CharField(db_index=True, max_length=120)),
                ('translated_html', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='translationcache',
            constraint=models.UniqueConstraint(fields=('content_hash', 'model_name'), name='uniq_translation_cache_hash_model'),
        ),
    ]
