# Generated by Django 4.2.27 on 2026-02-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0010_bookmark_bookmark_uniq_bookmark_per_user_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='anchor_char_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='anchor_text',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
